name: flutter_secure_storage_example
description: Demonstrates how to use the flutter_secure_storage plugin.

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter_secure_storage: ^10.2.0
  flutter_secure_storage_tvos:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
