#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html.
# Run `pod lib lint firebase_ai_tvos.podspec` to validate before publishing.
#
# Generated by `flutter-tvos plugin port`, then finished by hand. License holder: fluttertv.
#
Pod::Spec.new do |s|
  s.name             = 'firebase_ai_tvos'
  s.version          = '0.0.1'
  s.summary          = 'tvOS implementation of firebase_ai.'
  s.description      = <<-DESC
tvOS implementation of firebase_ai, the federated platform
package that ships native code targeting Apple tvOS.
                       DESC
  s.homepage         = 'https://github.com/fluttertv/plugins/tree/main/packages/firebase_ai_tvos'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'fluttertv' => 'noreply@fluttertv.dev' }
  s.source           = { :path => '.' }
  s.source_files     = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  # No Firebase native SDK dependency — firebase_ai's native side is a single
  # method-channel plugin (getPlatformHeaders); the AI calls are HTTPS from Dart.
  # tvOS 15.0 matches the rest of the Firebase _tvos family the app ships with.
  s.platform         = :tvos, '15.0'
  s.swift_version    = '5.0'

  # IMPORTANT: this podspec must not depend on the Flutter CocoaPod. That pod
  # does not declare tvOS support, so depending on it breaks `pod install` for
  # tvOS consumers. Flutter.framework is resolved via FRAMEWORK_SEARCH_PATHS.
  s.xcconfig         = {
    'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../Flutter"',
    'OTHER_SWIFT_FLAGS'      => '$(inherited) -DTARGET_OS_TV',
  }
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
end
